# -*- coding: utf-8 -*-
"""Ola mundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy0eyBJEqkuNDzCKSRov7r8iXDxTvgvM
"""

print("Olá, mundo")